name = "TransposeMatrix"
uuid = "1a2a01d2-c044-4ae4-8de1-e8ffaa2b5b19"
version = "0.1.0"
authors = ["Erik Schnetter <schnetter@gmail.com>"]

[deps]
SIMD = "fdea26ae-647d-5447-a871-4b548cad5224"

[compat]
SIMD = "3.7.2"
julia = "1.11"
